# Generated by Django 5.0.7 on 2024-07-31 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
